server:
  port: 8890
  
spring:  
  application:
    name: sleuth-service
    
#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
      
#ribbon:
#  eureka:
#    enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR